### ISSUE TITLE
Missing `./src/manifest` file

### ISSUE THREAD

**Issue by mikeselander** [humanmade/webpack-helpers#1]
Looks like a file might not have gotten committed, as `index.js` is [referencing `./src/manifest` file](https://github.com/humanmade/webpack-helpers/blob/master/index.js#L15), but that file isn't committed to the repo.

```
/Users/mikeselander/concentra/node_modules/webpack-cli/bin/cli.js:231
				throw err;
				^

Error: Cannot find module './src/manifest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/mikeselander/concentra/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/mikeselander/concentra/node_modules/@humanmade/webpack-helpers/index.js:15:12)
```

**Comment by kadamwhite** [comment]
Resolved in the latest releases; the file moved to `helpers/clean-on-exit.js`
