### ISSUE TITLE
Build fails if eslint or "stylish" eslint reporter are missing

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/webpack-helpers#16]
If eslint is missing, the build fails; but if the specific "stylish" eslint reporter is missing, the build also fails.
```
    ERROR in ./themes/myproject/src/frontend.js
    Module build failed (from ./node_modules/eslint-loader/index.js):
    Error: Cannot find module 'eslint/lib/formatters/stylish'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
        at Function.Module._load (internal/modules/cjs/loader.js:508:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
        at require (/hm/tmp/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at Object.module.exports (/hm/tmp/node_modules/eslint-loader/index.js:199:26)
```
This is not ideal because the build should work regardless of the specific eslint configuration in play. Either stylish should be bundled, or we should detect when it's not and not error.

**Comment by kadamwhite** [comment]
The stylish issue doesn't seem to be related to a separate package, but instead to the fact that eslint 6 is now out which has different file structure. I'd like to explore conditionally detecting for ESLint and only including the loader if we find it.
